### ISSUE TITLE
Sites | Revisions | BBTK > Make sure to use the dutch label

### ISSUE THREAD

**Issue by jgui1129** [jgui1129/UP-TO-DATE-WebDesign-Apps#198]
Best

 As discussed Friday, here are the comments.

 The following blogs do not have a photo in the overview. Well if you click it open:

https://www.bbtklimburg.be/2021/02/ipa-negotiations-geblokd.html
https://www.bbtklimburg.be/2021/02/bbtk-vragent-respect-voor-het.html

This podcast is suddenly in English, while it is made in Dutch.
https://www.bbtklimburg.be/2022/02/podcast-ons-loon.html

 
At the News tab, it has therefore been discussed that there would be a split with 4-5 topics, namely:
- Podcast
- (Events)
- Legislation / latest news
- Our members
- Union premium/reimbursements

The mp4 files for the podcasts have already been requested, as soon as I have them I will send them to you.

 In addition, we have also discussed creating a kind of advertisement on our website where people can register as a member by clicking on it. Our benefits etc. were therefore also mentioned under the tab becoming a member before they received the registration forms.

With the digital support tab we still end up with assistance at work, this can be arranged.
https://www.bbtklimburg.be/p/digitale-steun.html

 Then on our home page there is also the advice block rental disputes that is mentioned. It has been discussed that this would be converted to Services such as the first block.

Thank you for making the adjustments.

Kind regards 
<img width="1007" alt="Screen Shot 2022-03-08 at 9 51 24 AM" src="https://user-images.githubusercontent.com/29097518/157201424-b06b32ff-fbf6-4826-bd73-d581709dc7fb.png">

**Comment by renzoamoranto** [comment]
Hi @all, asking for assistance about these 3 remaining revisions from the client. Please explain what these revisions are

1. The mp4 files for the podcasts have already been requested, as soon as I have them I will send them to you.

2. In addition, we have also discussed creating a kind of advertisement on our website where people can register as a member by clicking on it. Our benefits etc. were therefore also mentioned under the tab becoming a member before they received the registration forms.

3. With the digital support tab we still end up with assistance at work, this can be arranged.
https://www.bbtklimburg.be/p/digitale-steun.html

4. Also, for the Nieuws page, the division of topic is done. I don't know which labels to put on blog posts.

Thank you!

Note: Some of the revisions are done except for the 3 comments.
