### ISSUE TITLE
Sites | Revisions | Senitas

### ISSUE THREAD

**Issue by jgui1129** [jgui1129/UP-TO-DATE-WebDesign-Apps#201]
Hi Jeric,

 As promised I went into the current site to see which pages we want to maintain and need to be build.

Hopefully this list below helps. If you have any questions, just let me know!!

 
Pages [senitas.com](http://senitas.com/) 

 

Design

In de media (based on the same page as series where we show a selection of the brands. When clicking on a brand the blogposts which are tagged both with ‘pers’ and the brandname will be shown) - https://senitas.com/pers/ (no need anymore to divide the press articles into magazines, events and persmap as we will show them all as blogs and add the video’s or links to a pressfolder inside the blog post.
Downloads (white papers) - https://senitas.com/downloads/ 
Privacy statement - https://senitas.com/privacy-statement/ 
Algemene voorwaarden - https://senitas.com/verkoopsvoorwaarden/ 
Icoone resultaten - https://senitas.com/icoone/resultaten/ url to /p/icoone/icoone-resultaten.html
Icoone locaties page that points to https://senitas-smartsite.blogspot.com/p/icoone-apparaat.html#icoone-stores 
Contact page with a CTA that leads to open the chat, see link that we currently use on [senitas.com/contact](http://senitas.com/contact) behind the button ‘chat met ons’.

Current blogposts on [senitas.com](http://senitas.com/), all to copy and paste into this site

**Comment by jgui1129** [comment]
<img width="639" alt="Schermafbeelding 2022-03-09 om 09 50 38" src="https://user-images.githubusercontent.com/29097518/157407282-51e54462-c9fc-43b3-b116-ddb770b688dc.png">

**Comment by aliza-utd** [comment]
All of the comments are resolved except 

- In de media (based on the same page as series where we show a selection of the brands. When clicking on a brand the blogposts which are tagged both with ‘pers’ and the brandname will be shown) - https://senitas.com/pers/ (no need anymore to divide the press articles into magazines, events and persmap as we will show them all as blogs and add the video’s or links to a pressfolder inside the blog post. 

This needs a custom solution where post label 'pers' is shown together with some label tags
